### ISSUE TITLE
No sirve HIVE (Connection Refused)

### ISSUE THREAD

**Issue by felipegerard** [ITAM-DS/big-data#105]
No funciona HIVE. Por alguna razón dice que la conexión fue rehusada :( Y sí está corriendo el hive-server2:

```
➜  ~  sudo service hive-server2 start
 * Hive Server2 is running
➜  ~  beeline -u jdbc:hive2://localhost:10000
showscan complete in 3ms
Connecting to jdbc:hive2://localhost:10000
Error: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10000: java.net.ConnectException: Conexión rehusada (state=08S01,code=0)
Beeline version 1.1.0-cdh5.4.0 by Apache Hive
0: jdbc:hive2://localhost:10000 (closed)> show tables;
No current connection
```

Busqué en Google qué podría ser sin éxito...

**UPDATE:** Cuando jala (está por determinarse por qué a veces jala y a veces no), da un error al intentar crear la tabla shakespeare:

```
0: jdbc:hive2://localhost:10000> show tables;
+-----------+--+
| tab_name  |
+-----------+--+
| ufos      |
+-----------+--+
1 row selected (0.034 seconds)
0: jdbc:hive2://localhost:10000> create table shakespeare(linea string);
Error: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Got exception: org.apache.hadoop.security.AccessControlException Permission denied: user=anonymous, access=WRITE, inode="/user/hive/warehouse":hive:supergroup:drwxrwxr-x
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkFsPermission(DefaultAuthorizationProvider.java:257)
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.check(DefaultAuthorizationProvider.java:238)
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.check(DefaultAuthorizationProvider.java:216)
	at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkPermission(DefaultAuthorizationProvider.java:145)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:138)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkPermission(FSNamesystem.java:6553)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkPermission(FSNamesystem.java:6535)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkAncestorAccess(FSNamesystem.java:6487)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirsInternal(FSNamesystem.java:4291)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirsInt(FSNamesystem.java:4261)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirs(FSNamesystem.java:4234)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.mkdirs(NameNodeRpcServer.java:817)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.mkdirs(AuthorizationProviderProxyClientProtocol.java:321)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.mkdirs(ClientNamenodeProtocolServerSideTranslatorPB.java:601)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:619)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2044)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2040)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2038)
) (state=08S01,code=1)
0: jdbc:hive2://localhost:10000>
```

**Comment by alfonsokim** [comment]
Mmm. Me pasó algo similar con impala.

¿qué dice la salida de `cat /etc/hosts`?
¿que dice la salida `netstat -apn | grep 10000`?

=)

**Comment by felipegerard** [comment]
No sé qué pasó... Hace rato sí jaló pero ahora ya no de nuevo. El dataset está creado con datos y todo:
```
➜  ~  kite-dataset show dataset:hive:/user/itam/datasets/ufos
{"Date_Time": "12/31/14 23:59", "City": "Wailuku", "State": "HI", "Shape": "Circle", "Duration": "20 minutes", "Summary": "Exactly one year to the date more red orange floating objects.", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 23:59", "City": "St. Thomas (U. S. Virgin Islands)", "State": "", "Shape": "Triangle", "Duration": "5 minutes", "Summary": "Red triangle seen over us Virgin Islands on New Year's Eve.", "Posted": "1/09/2015"}
{"Date_Time": "12/31/14 23:30", "City": "San Jose del Cabo (Baja California)(Mexico)", "State": "", "Shape": "Triangle", "Duration": "10 minutes", "Summary": "Two triangular lights over San Jose del Cabo New Year's eve. I was not  drinking.", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 23:30", "City": "Boynton Beach", "State": "FL", "Shape": "Light", "Duration": "1 minute", "Summary": "Orange light moves west, flickers, then takes off full speed out of sight.", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 23:30", "City": "Smyrna", "State": "GA", "Shape": "Disk", "Duration": "15 minutes", "Summary": "Very bright orange/red lights on disc shaped craft heading due south over  Atlanta on New Years Eve", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 23:15", "City": "Onancock", "State": "VA", "Shape": "Light", "Duration": "2-3 seconds", "Summary": "Fast bright light disapears with in a second", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 22:45", "City": "Bear Lake", "State": "UT", "Shape": "Sphere", "Duration": "5 minutes", "Summary": "Dark orange light that was stationary in the sky and turned from 1 light to  3 lights in a crescent shape.  Stayed in one place for ab", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 22:45", "City": "Somersworth", "State": "NH", "Shape": "Fireball", "Duration": "10 minutes", "Summary": "Two orange fireballs seen moving silently across the night sky in  Somersworth, NH.", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 22:15", "City": "Vancouver", "State": "WA", "Shape": "Light", "Duration": "15 minutes", "Summary": "Orange orbs seen in southeast sky over Vancouver WA on New Years Eve at  about 10:15pm", "Posted": "1/07/2015"}
{"Date_Time": "12/31/14 22:00", "City": "Taos", "State": "NM", "Shape": "Light", "Duration": "Several minutes", "Summary": "Large ball of orange/yellow light in Taos, NM.", "Posted": "1/07/2015"}
```

Pero sale esto cuando intento entrar a HIVE:

```
➜  ~  beeline -u jdbc:hive2://localhost:10000
scan complete in 4ms
Connecting to jdbc:hive2://localhost:10000
Error: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10000: java.net.ConnectException: Conexión rehusada (state=08S01,code=0)
Beeline version 1.1.0-cdh5.4.0 by Apache Hive
0: jdbc:hive2://localhost:10000 (closed)>
```

De verdad está rarísimo que hace rato sí jaló! Sobre lo que pediste, el grep no da nada. Puse el head de lo que da sin grep para que veas que sí jala:

```
➜  ~  cat /etc/hosts
172.17.0.1	0b688da1b693
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
➜  ~  sudo netstat -apn | head
Conexiones activas de Internet (servidores y establecidos)
Proto  Recib Enviad Dirección local         Dirección remota       Estado       PID/Program name
tcp        0      0 0.0.0.0:50111           0.0.0.0:*               ESCUCHAR    -
tcp        0      0 127.0.0.1:10020         0.0.0.0:*               ESCUCHAR    -
tcp        0      0 0.0.0.0:50020           0.0.0.0:*               ESCUCHAR    -
tcp        0      0 0.0.0.0:25000           0.0.0.0:*               ESCUCHAR    -
tcp        0      0 0.0.0.0:50090           0.0.0.0:*               ESCUCHAR    -
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               ESCUCHAR    -
tcp        0      0 0.0.0.0:2122            0.0.0.0:*               ESCUCHAR    29/sshd
tcp        0      0 127.0.0.1:19888         0.0.0.0:*               ESCUCHAR    -
➜  ~  sudo netstat -apn | grep 10000
➜  ~
```

Gracias por la ayuda! De verdad no sé qué es lo que pasa. Está rarísimo que hace rato sí jaló, no? Estaba en el Starbucks y ahora en mi casa. No sé si tendrá que ver con alguna otra red. La verdad no sé mucho de redes...

\(*-*)/  (; n ;)

**Comment by alfonsokim** [comment]
Si, está raro...

De entrada creo que esta línea del `/etc/hosts` está haciendo ruido: `172.17.0.1  0b688da1b693`, cámbiala a `127.0.0.1  0b688da1b693` (respalda el archivo o comenta la línea original antes!). Yo tuve que reiniciar el contenedor para que tomara los cambios.

Luego. Más raro está que no tengas nada escuchando en el puerto 10000. ¿qué dice `service hive-server2 status`? Según yo no había que levantar o bajar el servicio a mano. El proceso de booteo lo hace.

**Comment by felipegerard** [comment]
De nuevo funciona. Y te prometo que no hice nada. Esta vez inicié el contenedor tal cuál y ya funcionó. Mi historial (el exit es de la sesión pasada):
```
  303  exit
  304  history
  305  beeline -u jdbc:hive2://localhost:10000
  306  cat /etc/hosts
  307  beeline -u jdbc:hive2://localhost:10000
```

Y ahora el resultado (omití el primer `beeline`, aunque también jaló):

```
➜  ~  cat /etc/hosts
172.17.0.1	0b688da1b693
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
➜  ~  beeline -u jdbc:hive2://localhost:10000
scan complete in 4ms
Connecting to jdbc:hive2://localhost:10000
Connected to: Apache Hive (version 1.1.0-cdh5.4.0)
Driver: Hive JDBC (version 1.1.0-cdh5.4.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Beeline version 1.1.0-cdh5.4.0 by Apache Hive
0: jdbc:hive2://localhost:10000> show tables;
+-----------+--+
| tab_name  |
+-----------+--+
| ufos      |
+-----------+--+
1 row selected (1.725 seconds)
0: jdbc:hive2://localhost:10000> select Date_Time, State, Shape from ufos limit 5;
+-----------------+--------+-----------+--+
|    date_time    | state  |   shape   |
+-----------------+--------+-----------+--+
| 11/30/14 21:45  | PA     | Oval      |
| 11/30/14 21:30  | AZ     | Unknown   |
| 11/30/14 21:00  | TN     | Light     |
| 11/30/14 20:20  | CA     | Light     |
| 11/30/14 20:03  |        | Fireball  |
+-----------------+--------+-----------+--+
5 rows selected (1.75 seconds)
```

Como se ve, jaló perfectamente y no tuve que cambiar /etc/hosts... El servicio de hive-server2 está corriendo:

```
➜  ~  sudo service hive-server2 status
[sudo] password for itam:
 * Hive Server2 is running
```

Y lo que sí cambió es que ya está escuchando en el puerto 10000:

```
➜  ~  sudo netstat -apn | grep 10000
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               ESCUCHAR    -
```

Lo que se me ocurre es que por alguna razón en las veces que no jala no puede echar a andar el servicio, pero la vez pasada que no jalaba, aunque no probé lo de `service hive-server2 status`, usé `top` y sí estaba corriendo HIVE. Está súper raro, no? Seguro Adolfo le echará la culpa a la mac u.u Déjenla pobrecita es viejita jajajaj

**Comment by nanounanue** [comment]
Mmmm

Como siempre @felipegerard mezclando `issues` ¿Qué cuesta separarlos?

NO tiene que ver con el `/etc/hosts` para que se conecte debe de estar levantado el servicio de `hive-metastore` , `hive-server2` y el  `hive-webhcat-server` ¿Están ejecutándose?
(Lo puedes ver con `status` en el comando `service`) Si se caen, probablemente te quedes sin  memoria `RAM`...

Respecto a lo de la creacíón de la tabla es un problema de permisos (ahí dice...)

Por último no es necesario usar `dataset:hive: ...` con `kite`, por default  lo hace (y no pasa eso con eñ `hdfs`).

**Comment by felipegerard** [comment]
Ahorita sí están corriendo. Aunque no lo chequé las veces que no corrió porque no sabía. Pero cuando vuelva a pasar (nunca, espero) lo checo. Y lo de permisos, entonces le cambio los permisos a la carpeta que dice ahí?

**Comment by felipegerard** [comment]
Investigué más y creo que el tema es que MapReduce no está jalando, porque `pig` también se queda trabado en 0% al intentar cualquier cosa que requiera MapReduce:

```
➜  ~  pig -useHCatalog
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2015-05-19 16:58:29,853 [main] INFO  org.apache.pig.Main - Apache Pig version 0.12.0-cdh5.4.0 (rUnversioned directory) compiled Apr 21 2015, 12:19:15
2015-05-19 16:58:29,854 [main] INFO  org.apache.pig.Main - Logging error messages to: /home/itam/pig_1432054709764.log
2015-05-19 16:58:30,485 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:30,486 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:30,486 [main] INFO  org.apache.pig.backend.hadoop.executionengine.HExecutionEngine - Connecting to hadoop file system at: hdfs://localhost:8020
2015-05-19 16:58:33,834 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:33,834 [main] INFO  org.apache.pig.backend.hadoop.executionengine.HExecutionEngine - Connecting to map-reduce job tracker at: localhost:8021
2015-05-19 16:58:33,834 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:33,913 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:33,916 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:33,983 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:33,985 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:34,046 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,047 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:34,107 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,108 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:34,166 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,166 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:34,241 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,243 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:34,298 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,299 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:34,341 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,342 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
grunt> REGISTER hdfs://localhost/user/itam/lib/datafu-1.1.0-cdh5.4.0.jar
2015-05-19 16:58:34,425 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,426 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
grunt> REGISTER hdfs://localhost/user/itam/lib/piggybank.jar
2015-05-19 16:58:34,873 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,873 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:34,898 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,898 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
grunt> REGISTER hdfs://localhost/user/itam/lib/avro-1.7.6-cdh5.4.0.jar
2015-05-19 16:58:34,992 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:34,993 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
grunt> REGISTER hdfs://localhost/user/itam/lib/snappy-java-1.0.5.jar
2015-05-19 16:58:35,059 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:35,060 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
grunt> REGISTER hdfs://localhost/user/itam/lib/json-simple-1.1.jar
2015-05-19 16:58:35,139 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:35,139 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
grunt> ufos_dic = LOAD 'experimentos/UFO-Dic-2014.tsv' using PigStorage('\t')
>>             AS (Timestamp:chararray,
>>                 City:chararray, State:chararray,
>>                 Shape:chararray, Duration:chararray,
>>                 Summary:chararray, Posted:chararray);
grunt>
grunt> DESCRIBE ufos_dic;
ufos_dic: {Timestamp: chararray,City: chararray,State: chararray,Shape: chararray,Duration: chararray,Summary: chararray,Posted: chararray}
grunt> head = LIMIT ufos_dic 5;
grunt> DUMP head;
2015-05-19 16:58:44,305 [main] INFO  org.apache.pig.tools.pigstats.ScriptState - Pig features used in the script: LIMIT
2015-05-19 16:58:44,366 [main] INFO  org.apache.pig.newplan.logical.optimizer.LogicalPlanOptimizer - {RULES_ENABLED=[AddForEach, ColumnMapKeyPrune, DuplicateForEachColumnRewrite, GroupByConstParallelSetter, ImplicitSplitInserter, LimitOptimizer, LoadTypeCastInserter, MergeFilter, MergeForEach, NewPartitionFilterOptimizer, PushDownForEachFlatten, PushUpFilter, SplitFilter, StreamTypeCastInserter], RULES_DISABLED=[FilterLogicExpressionSimplifier, PartitionFilterOptimizer]}
2015-05-19 16:58:44,593 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MRCompiler - File concatenation threshold: 100 optimistic? false
2015-05-19 16:58:44,647 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MultiQueryOptimizer - MR plan size before optimization: 2
2015-05-19 16:58:44,647 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MultiQueryOptimizer - MR plan size after optimization: 2
2015-05-19 16:58:44,738 [main] INFO  org.apache.hadoop.yarn.client.RMProxy - Connecting to ResourceManager at /0.0.0.0:8032
2015-05-19 16:58:45,103 [main] INFO  org.apache.pig.tools.pigstats.ScriptState - Pig script settings are added to the job
2015-05-19 16:58:45,179 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.reduce.markreset.buffer.percent is deprecated. Instead, use mapreduce.reduce.markreset.buffer.percent
2015-05-19 16:58:45,179 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - mapred.job.reduce.markreset.buffer.percent is not set, set to default 0.3
2015-05-19 16:58:45,179 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.output.compress is deprecated. Instead, use mapreduce.output.fileoutputformat.compress
2015-05-19 16:58:45,182 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - Reduce phase detected, estimating # of required reducers.
2015-05-19 16:58:45,182 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - Setting Parallelism to 1
2015-05-19 16:58:45,182 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.reduce.tasks is deprecated. Instead, use mapreduce.job.reduces
2015-05-19 16:58:45,847 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - creating jar file Job5814856547727914842.jar
2015-05-19 16:58:51,427 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - jar file Job5814856547727914842.jar created
2015-05-19 16:58:51,427 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.jar is deprecated. Instead, use mapreduce.job.jar
2015-05-19 16:58:51,459 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - Setting up single store job
2015-05-19 16:58:51,471 [main] INFO  org.apache.pig.data.SchemaTupleFrontend - Key [pig.schematuple] is false, will not generate code.
2015-05-19 16:58:51,471 [main] INFO  org.apache.pig.data.SchemaTupleFrontend - Starting process to move generated code to distributed cache
2015-05-19 16:58:51,471 [main] INFO  org.apache.pig.data.SchemaTupleFrontend - Setting key [pig.schematuple.classes] with classes to deserialize []
2015-05-19 16:58:51,594 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 1 map-reduce job(s) waiting for submission.
2015-05-19 16:58:51,594 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker.http.address is deprecated. Instead, use mapreduce.jobtracker.http.address
2015-05-19 16:58:51,595 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-05-19 16:58:51,614 [JobControl] INFO  org.apache.hadoop.yarn.client.RMProxy - Connecting to ResourceManager at /0.0.0.0:8032
2015-05-19 16:58:51,671 [JobControl] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-05-19 16:58:52,038 [JobControl] INFO  org.apache.hadoop.mapreduce.lib.input.FileInputFormat - Total input paths to process : 1
2015-05-19 16:58:52,038 [JobControl] INFO  org.apache.pig.backend.hadoop.executionengine.util.MapRedUtil - Total input paths to process : 1
2015-05-19 16:58:52,066 [JobControl] INFO  org.apache.pig.backend.hadoop.executionengine.util.MapRedUtil - Total input paths (combined) to process : 1
2015-05-19 16:58:52,145 [JobControl] INFO  org.apache.hadoop.mapreduce.JobSubmitter - number of splits:1
2015-05-19 16:58:52,441 [JobControl] INFO  org.apache.hadoop.mapreduce.JobSubmitter - Submitting tokens for job: job_1432053667641_0003
2015-05-19 16:58:52,888 [JobControl] INFO  org.apache.hadoop.yarn.client.api.impl.YarnClientImpl - Submitted application application_1432053667641_0003
2015-05-19 16:58:52,954 [JobControl] INFO  org.apache.hadoop.mapreduce.Job - The url to track the job: http://0aa234502399:8088/proxy/application_1432053667641_0003/
2015-05-19 16:58:52,955 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - HadoopJobId: job_1432053667641_0003
2015-05-19 16:58:52,955 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Processing aliases head,ufos_dic
2015-05-19 16:58:52,956 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - detailed locations: M: ufos_dic[1,11],head[6,7] C:  R:
2015-05-19 16:58:52,956 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - More information at: http://localhost:50030/jobdetails.jsp?jobid=job_1432053667641_0003
2015-05-19 16:58:53,007 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 0% complete
```

Al principio pensé que podría ser algo que tiene que ver con [esto](http://stackoverflow.com/questions/10843117/pig-dump-gets-stuck-in-group), pero chequé `/etc/hadoop/conf.pseudo/mapred-site.xml` y no tiene lo de _true_ que dice en el post. _Creo_ que encontré una posible [solución](https://issues.apache.org/jira/browse/YARN-300), pero no sé cómo llevarla a cabo y no quiero hacer alguna tontería. Lo curioso es que intenté generar un nuevo contenedor y seguía teniendo el problema! O sea creé los datasets sin problema y todo. De hecho, otra cosa rara es que cuando corría MapReduce (ie. Pig y Hive), según recuerdo no corría bien Impala, pero ahora que no corren esos dos, Impala sí corre! Está raro, no?

**Comment by nanounanue** [comment]
¿Volviste a mezclar los issues?

Por favor corrige abre uno nuevo.

**Comment by felipegerard** [comment]
Pero no entiendo... Ambos (pig y hive) tienen el mismo problema. En ambos
el tema es que no corre MapReduce, no? O sea dejaron de funcionar al mismo
tiempo. Lo de impala fue un comentario relevante nada más, que ahora sí
funciona :(
